import Database from "better-sqlite3";
import path from "path";

const DB_PATH = path.join(process.cwd(), "baseball.db");
const db = new Database(DB_PATH);
db.pragma("journal_mode = WAL");

// Create tables
db.exec(`
  DROP TABLE IF EXISTS user_school_data;
  DROP TABLE IF EXISTS schools;

  CREATE TABLE schools (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    mascot TEXT,
    city TEXT,
    state TEXT,
    zip TEXT,
    latitude REAL,
    longitude REAL,
    division TEXT NOT NULL,
    public_private TEXT,
    conference TEXT,
    current_ranking INTEGER,
    tuition INTEGER,
    instagram TEXT,
    x_account TEXT,
    head_coach_name TEXT,
    head_coach_email TEXT,
    assistant_coach_name TEXT,
    assistant_coach_email TEXT,
    website TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
  );

  CREATE TABLE user_school_data (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    school_id INTEGER NOT NULL UNIQUE,
    priority INTEGER DEFAULT 0 CHECK(priority >= 0 AND priority <= 5),
    notes TEXT DEFAULT '',
    last_contacted DATE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (school_id) REFERENCES schools(id)
  );

  CREATE INDEX idx_schools_division ON schools(division);
  CREATE INDEX idx_schools_state ON schools(state);
  CREATE INDEX idx_schools_conference ON schools(conference);
  CREATE INDEX idx_schools_name ON schools(name);
`);

interface SchoolSeed {
  name: string;
  mascot: string;
  city: string;
  state: string;
  zip: string;
  lat: number;
  lng: number;
  division: string;
  publicPrivate: string;
  conference: string;
  ranking: number | null;
  tuition: number;
  instagram: string;
  xAccount: string;
  headCoach: string;
  headCoachEmail: string;
  asstCoach: string;
  asstCoachEmail: string;
  website: string;
}

const schools: SchoolSeed[] = [
  // ============================================
  // NCAA DIVISION I PROGRAMS
  // ============================================
  // SEC
  { name: "LSU", mascot: "Tigers", city: "Baton Rouge", state: "LA", zip: "70803", lat: 30.4133, lng: -91.1800, division: "D1", publicPrivate: "Public", conference: "SEC", ranking: 1, tuition: 11962, instagram: "@lsubaseball", xAccount: "@LSUbaseball", headCoach: "Jay Johnson", headCoachEmail: "baseball@lsu.edu", asstCoach: "Dan Fitzgerald", asstCoachEmail: "baseball@lsu.edu", website: "https://lsusports.net/sports/baseball" },
  { name: "Tennessee", mascot: "Volunteers", city: "Knoxville", state: "TN", zip: "37996", lat: 35.9544, lng: -83.9295, division: "D1", publicPrivate: "Public", conference: "SEC", ranking: 2, tuition: 13244, instagram: "@vol_baseball", xAccount: "@Vol_Baseball", headCoach: "Tony Vitello", headCoachEmail: "baseball@utk.edu", asstCoach: "Josh Elander", asstCoachEmail: "baseball@utk.edu", website: "https://utsports.com/sports/baseball" },
  { name: "Texas A&M", mascot: "Aggies", city: "College Station", state: "TX", zip: "77843", lat: 30.6187, lng: -96.3365, division: "D1", publicPrivate: "Public", conference: "SEC", ranking: 3, tuition: 12413, instagram: "@aggiebaseball", xAccount: "@AggieBaseball", headCoach: "Jim Schlossnagle", headCoachEmail: "baseball@athletics.tamu.edu", asstCoach: "Nate Thompson", asstCoachEmail: "baseball@athletics.tamu.edu", website: "https://12thman.com/sports/baseball" },
  { name: "Florida", mascot: "Gators", city: "Gainesville", state: "FL", zip: "32611", lat: 29.6516, lng: -82.3248, division: "D1", publicPrivate: "Public", conference: "SEC", ranking: 4, tuition: 6380, instagram: "@gatorsbbq", xAccount: "@GatorsBB", headCoach: "Kevin O'Sullivan", headCoachEmail: "baseball@gators.ufl.edu", asstCoach: "Craig Bell", asstCoachEmail: "baseball@gators.ufl.edu", website: "https://floridagators.com/sports/baseball" },
  { name: "Vanderbilt", mascot: "Commodores", city: "Nashville", state: "TN", zip: "37240", lat: 36.1447, lng: -86.8027, division: "D1", publicPrivate: "Private", conference: "SEC", ranking: 5, tuition: 60348, instagram: "@vandybaseball", xAccount: "@VandyBoys", headCoach: "Tim Corbin", headCoachEmail: "baseball@vanderbilt.edu", asstCoach: "Mike Baxter", asstCoachEmail: "baseball@vanderbilt.edu", website: "https://vucommodores.com/sports/baseball" },
  { name: "Arkansas", mascot: "Razorbacks", city: "Fayetteville", state: "AR", zip: "72701", lat: 36.0676, lng: -94.1748, division: "D1", publicPrivate: "Public", conference: "SEC", ranking: 8, tuition: 9658, instagram: "@razorbackbsb", xAccount: "@RazorbackBSB", headCoach: "Dave Van Horn", headCoachEmail: "baseball@uark.edu", asstCoach: "Nate Thompson", asstCoachEmail: "baseball@uark.edu", website: "https://arkansasrazorbacks.com/sports/baseball" },
  { name: "Ole Miss", mascot: "Rebels", city: "Oxford", state: "MS", zip: "38677", lat: 34.3665, lng: -89.5186, division: "D1", publicPrivate: "Public", conference: "SEC", ranking: 10, tuition: 8790, instagram: "@oloissbaseball", xAccount: "@OleMissBSB", headCoach: "Mike Bianco", headCoachEmail: "baseball@olemiss.edu", asstCoach: "Mike Federico", asstCoachEmail: "baseball@olemiss.edu", website: "https://olemisssports.com/sports/baseball" },
  { name: "Mississippi State", mascot: "Bulldogs", city: "Starkville", state: "MS", zip: "39762", lat: 33.4557, lng: -88.7893, division: "D1", publicPrivate: "Public", conference: "SEC", ranking: 15, tuition: 9258, instagram: "@hailstatebs", xAccount: "@HailStateBB", headCoach: "Chris Lemonis", headCoachEmail: "baseball@msstate.edu", asstCoach: "Jake Gautreau", asstCoachEmail: "baseball@msstate.edu", website: "https://hailstate.com/sports/baseball" },
  { name: "South Carolina", mascot: "Gamecocks", city: "Columbia", state: "SC", zip: "29208", lat: 33.9940, lng: -81.0273, division: "D1", publicPrivate: "Public", conference: "SEC", ranking: 18, tuition: 12688, instagram: "@gamecockbsb", xAccount: "@GamecockBaseb1", headCoach: "Mark Kingston", headCoachEmail: "baseball@sc.edu", asstCoach: "Trip Couch", asstCoachEmail: "baseball@sc.edu", website: "https://gamecocksonline.com/sports/baseball" },
  { name: "Auburn", mascot: "Tigers", city: "Auburn", state: "AL", zip: "36849", lat: 32.6013, lng: -85.4897, division: "D1", publicPrivate: "Public", conference: "SEC", ranking: 20, tuition: 11826, instagram: "@auburnbaseball", xAccount: "@AuburnBaseball", headCoach: "Butch Thompson", headCoachEmail: "baseball@auburn.edu", asstCoach: "Karl Nonemaker", asstCoachEmail: "baseball@auburn.edu", website: "https://auburntigers.com/sports/baseball" },
  { name: "Alabama", mascot: "Crimson Tide", city: "Tuscaloosa", state: "AL", zip: "35487", lat: 33.2098, lng: -87.5692, division: "D1", publicPrivate: "Public", conference: "SEC", ranking: null, tuition: 11100, instagram: "@alabamabsb", xAccount: "@AlabamaBSB", headCoach: "Rob Vaughn", headCoachEmail: "baseball@ua.edu", asstCoach: "Jason Jackson", asstCoachEmail: "baseball@ua.edu", website: "https://rolltide.com/sports/baseball" },
  { name: "Georgia", mascot: "Bulldogs", city: "Athens", state: "GA", zip: "30602", lat: 33.9480, lng: -83.3773, division: "D1", publicPrivate: "Public", conference: "SEC", ranking: 22, tuition: 12080, instagram: "@ugabaseball", xAccount: "@BaseballUGA", headCoach: "Wes Johnson", headCoachEmail: "baseball@uga.edu", asstCoach: "Sean Kenny", asstCoachEmail: "baseball@uga.edu", website: "https://georgiadogs.com/sports/baseball" },
  { name: "Kentucky", mascot: "Wildcats", city: "Lexington", state: "KY", zip: "40506", lat: 38.0317, lng: -84.5040, division: "D1", publicPrivate: "Public", conference: "SEC", ranking: null, tuition: 12360, instagram: "@ukbaseball", xAccount: "@UKBaseball", headCoach: "Nick Mingione", headCoachEmail: "baseball@uky.edu", asstCoach: "Todd Guilliams", asstCoachEmail: "baseball@uky.edu", website: "https://ukathletics.com/sports/baseball" },
  { name: "Missouri", mascot: "Tigers", city: "Columbia", state: "MO", zip: "65211", lat: 38.9404, lng: -92.3277, division: "D1", publicPrivate: "Public", conference: "SEC", ranking: null, tuition: 11506, instagram: "@mizzobaseball", xAccount: "@MizzouBaseball", headCoach: "Steve Bieser", headCoachEmail: "baseball@missouri.edu", asstCoach: "Jeric Ciccarello", asstCoachEmail: "baseball@missouri.edu", website: "https://mutigers.com/sports/baseball" },
  { name: "Texas", mascot: "Longhorns", city: "Austin", state: "TX", zip: "78712", lat: 30.2849, lng: -97.7341, division: "D1", publicPrivate: "Public", conference: "SEC", ranking: 6, tuition: 11448, instagram: "@texasbaseball", xAccount: "@TexasBaseball", headCoach: "David Pierce", headCoachEmail: "baseball@athletics.utexas.edu", asstCoach: "Sean Allen", asstCoachEmail: "baseball@athletics.utexas.edu", website: "https://texassports.com/sports/baseball" },
  { name: "Oklahoma", mascot: "Sooners", city: "Norman", state: "OK", zip: "73019", lat: 35.2226, lng: -97.4395, division: "D1", publicPrivate: "Public", conference: "SEC", ranking: null, tuition: 11338, instagram: "@ou_baseball", xAccount: "@OU_Baseball", headCoach: "Skip Johnson", headCoachEmail: "baseball@ou.edu", asstCoach: "Clay Van Hook", asstCoachEmail: "baseball@ou.edu", website: "https://soonersports.com/sports/baseball" },

  // ACC
  { name: "Wake Forest", mascot: "Demon Deacons", city: "Winston-Salem", state: "NC", zip: "27109", lat: 36.1336, lng: -80.2779, division: "D1", publicPrivate: "Private", conference: "ACC", ranking: 7, tuition: 61788, instagram: "@waborestbaseball", xAccount: "@WakeBaseball", headCoach: "Tom Walter", headCoachEmail: "baseball@wfu.edu", asstCoach: "Bill Cilento", asstCoachEmail: "baseball@wfu.edu", website: "https://godeacs.com/sports/baseball" },
  { name: "Virginia", mascot: "Cavaliers", city: "Charlottesville", state: "VA", zip: "22904", lat: 38.0336, lng: -78.5080, division: "D1", publicPrivate: "Public", conference: "ACC", ranking: 9, tuition: 19014, instagram: "@uvabaseball", xAccount: "@UVABaseball", headCoach: "Brian O'Connor", headCoachEmail: "baseball@virginia.edu", asstCoach: "Drew Dickinson", asstCoachEmail: "baseball@virginia.edu", website: "https://virginiasports.com/sports/baseball" },
  { name: "Clemson", mascot: "Tigers", city: "Clemson", state: "SC", zip: "29634", lat: 34.6834, lng: -82.8374, division: "D1", publicPrivate: "Public", conference: "ACC", ranking: 11, tuition: 15558, instagram: "@clemsonbaseball", xAccount: "@ClemsonBaseball", headCoach: "Erik Bakich", headCoachEmail: "baseball@clemson.edu", asstCoach: "Andrew See", asstCoachEmail: "baseball@clemson.edu", website: "https://clemsontigers.com/sports/baseball" },
  { name: "NC State", mascot: "Wolfpack", city: "Raleigh", state: "NC", zip: "27695", lat: 35.7872, lng: -78.6705, division: "D1", publicPrivate: "Public", conference: "ACC", ranking: 14, tuition: 9128, instagram: "@packbaseball", xAccount: "@NCStateBaseball", headCoach: "Elliott Avent", headCoachEmail: "baseball@ncsu.edu", asstCoach: "Chris Hart", asstCoachEmail: "baseball@ncsu.edu", website: "https://gopack.com/sports/baseball" },
  { name: "Florida State", mascot: "Seminoles", city: "Tallahassee", state: "FL", zip: "32306", lat: 30.4419, lng: -84.2985, division: "D1", publicPrivate: "Public", conference: "ACC", ranking: 12, tuition: 6517, instagram: "@fsub_baseball", xAccount: "@FSUBaseball", headCoach: "Link Jarrett", headCoachEmail: "baseball@fsu.edu", asstCoach: "Mike Martin Jr.", asstCoachEmail: "baseball@fsu.edu", website: "https://seminoles.com/sports/baseball" },
  { name: "North Carolina", mascot: "Tar Heels", city: "Chapel Hill", state: "NC", zip: "27599", lat: 35.9049, lng: -79.0469, division: "D1", publicPrivate: "Public", conference: "ACC", ranking: 16, tuition: 8980, instagram: "@diamondheels", xAccount: "@DiamondHeels", headCoach: "Scott Forbes", headCoachEmail: "baseball@unc.edu", asstCoach: "Jesse Wierzbicki", asstCoachEmail: "baseball@unc.edu", website: "https://goheels.com/sports/baseball" },
  { name: "Duke", mascot: "Blue Devils", city: "Durham", state: "NC", zip: "27708", lat: 36.0014, lng: -78.9382, division: "D1", publicPrivate: "Private", conference: "ACC", ranking: null, tuition: 63054, instagram: "@dukebaseball", xAccount: "@DukeBASE", headCoach: "Chris Pollard", headCoachEmail: "baseball@duke.edu", asstCoach: "Josh Jordan", asstCoachEmail: "baseball@duke.edu", website: "https://goduke.com/sports/baseball" },
  { name: "Miami (FL)", mascot: "Hurricanes", city: "Coral Gables", state: "FL", zip: "33146", lat: 25.7215, lng: -80.2684, division: "D1", publicPrivate: "Private", conference: "ACC", ranking: 13, tuition: 57194, instagram: "@caaboraseball", xAccount: "@CanesBaseball", headCoach: "Gino DiMare", headCoachEmail: "baseball@miami.edu", asstCoach: "Norberto Lopez", asstCoachEmail: "baseball@miami.edu", website: "https://miamihurricanes.com/sports/baseball" },
  { name: "Georgia Tech", mascot: "Yellow Jackets", city: "Atlanta", state: "GA", zip: "30332", lat: 33.7756, lng: -84.3963, division: "D1", publicPrivate: "Public", conference: "ACC", ranking: null, tuition: 12682, instagram: "@gtbaseball", xAccount: "@GTBaseball", headCoach: "Danny Hall", headCoachEmail: "baseball@athletics.gatech.edu", asstCoach: "James Ramsey", asstCoachEmail: "baseball@athletics.gatech.edu", website: "https://ramblinwreck.com/sports/baseball" },
  { name: "Virginia Tech", mascot: "Hokies", city: "Blacksburg", state: "VA", zip: "24061", lat: 37.2296, lng: -80.4139, division: "D1", publicPrivate: "Public", conference: "ACC", ranking: null, tuition: 14066, instagram: "@hokiesbaseball", xAccount: "@HokiesBaseball", headCoach: "John Szefc", headCoachEmail: "baseball@vt.edu", asstCoach: "Ryan Fecteau", asstCoachEmail: "baseball@vt.edu", website: "https://hokiesports.com/sports/baseball" },
  { name: "Pittsburgh", mascot: "Panthers", city: "Pittsburgh", state: "PA", zip: "15260", lat: 40.4443, lng: -79.9608, division: "D1", publicPrivate: "Public", conference: "ACC", ranking: null, tuition: 19718, instagram: "@pittbaseball", xAccount: "@Pitt_BASE", headCoach: "Mike Bell", headCoachEmail: "baseball@athletics.pitt.edu", asstCoach: "Pat Livingston", asstCoachEmail: "baseball@athletics.pitt.edu", website: "https://pittsburghpanthers.com/sports/baseball" },
  { name: "Louisville", mascot: "Cardinals", city: "Louisville", state: "KY", zip: "40292", lat: 38.2116, lng: -85.7584, division: "D1", publicPrivate: "Public", conference: "ACC", ranking: 17, tuition: 12246, instagram: "@louisvillebsb", xAccount: "@LouisvilleBSB", headCoach: "Dan McDonnell", headCoachEmail: "baseball@louisville.edu", asstCoach: "Roger Williams", asstCoachEmail: "baseball@louisville.edu", website: "https://gocards.com/sports/baseball" },
  { name: "Notre Dame", mascot: "Fighting Irish", city: "Notre Dame", state: "IN", zip: "46556", lat: 41.7002, lng: -86.2379, division: "D1", publicPrivate: "Private", conference: "ACC", ranking: null, tuition: 60301, instagram: "@ndbaseball", xAccount: "@NDBaseball", headCoach: "Shawn Stiffler", headCoachEmail: "baseball@nd.edu", asstCoach: "Rich Wallace", asstCoachEmail: "baseball@nd.edu", website: "https://und.com/sports/baseball" },
  { name: "Stanford", mascot: "Cardinal", city: "Stanford", state: "CA", zip: "94305", lat: 37.4275, lng: -122.1697, division: "D1", publicPrivate: "Private", conference: "ACC", ranking: 19, tuition: 61731, instagram: "@stanfordbase", xAccount: "@StanfordBSB", headCoach: "David Esquer", headCoachEmail: "baseball@stanford.edu", asstCoach: "Thomas Eager", asstCoachEmail: "baseball@stanford.edu", website: "https://gostanford.com/sports/baseball" },
  { name: "California", mascot: "Golden Bears", city: "Berkeley", state: "CA", zip: "94720", lat: 37.8719, lng: -122.2585, division: "D1", publicPrivate: "Public", conference: "ACC", ranking: null, tuition: 14312, instagram: "@calbaseball", xAccount: "@CalBaseball", headCoach: "Mike Neu", headCoachEmail: "baseball@cal.berkeley.edu", asstCoach: "David Nakama", asstCoachEmail: "baseball@cal.berkeley.edu", website: "https://calbears.com/sports/baseball" },
  { name: "SMU", mascot: "Mustangs", city: "Dallas", state: "TX", zip: "75205", lat: 32.8431, lng: -96.7850, division: "D1", publicPrivate: "Private", conference: "ACC", ranking: null, tuition: 61510, instagram: "@smubaseball", xAccount: "@SMUBaseball", headCoach: "Travis Jewett", headCoachEmail: "baseball@smu.edu", asstCoach: "Danny Clark", asstCoachEmail: "baseball@smu.edu", website: "https://smumustangs.com/sports/baseball" },
  { name: "Boston College", mascot: "Eagles", city: "Chestnut Hill", state: "MA", zip: "02467", lat: 42.3355, lng: -71.1685, division: "D1", publicPrivate: "Private", conference: "ACC", ranking: null, tuition: 62950, instagram: "@bcbaseball", xAccount: "@BCBirdball", headCoach: "Mike Gambino", headCoachEmail: "baseball@bc.edu", asstCoach: "Alex Trahan", asstCoachEmail: "baseball@bc.edu", website: "https://bceagles.com/sports/baseball" },
  { name: "Syracuse", mascot: "Orange", city: "Syracuse", state: "NY", zip: "13244", lat: 43.0392, lng: -76.1351, division: "D1", publicPrivate: "Private", conference: "ACC", ranking: null, tuition: 59534, instagram: "@cusebaseball", xAccount: "@CuseBaseball", headCoach: "Jono Armand", headCoachEmail: "baseball@syr.edu", asstCoach: "Kevin Connolly", asstCoachEmail: "baseball@syr.edu", website: "https://cuse.com/sports/baseball" },

  // Big 12
  { name: "TCU", mascot: "Horned Frogs", city: "Fort Worth", state: "TX", zip: "76129", lat: 32.7098, lng: -97.3628, division: "D1", publicPrivate: "Private", conference: "Big 12", ranking: 21, tuition: 55760, instagram: "@tcubaseball", xAccount: "@TCU_Baseball", headCoach: "Kirk Saarloos", headCoachEmail: "baseball@tcu.edu", asstCoach: "Bill Mosiello", asstCoachEmail: "baseball@tcu.edu", website: "https://gofrogs.com/sports/baseball" },
  { name: "Oklahoma State", mascot: "Cowboys", city: "Stillwater", state: "OK", zip: "74078", lat: 36.1156, lng: -97.0584, division: "D1", publicPrivate: "Public", conference: "Big 12", ranking: 23, tuition: 9018, instagram: "@cowboybaseball", xAccount: "@OSUBaseball", headCoach: "Josh Holliday", headCoachEmail: "baseball@okstate.edu", asstCoach: "Marty Lees", asstCoachEmail: "baseball@okstate.edu", website: "https://okstate.com/sports/baseball" },
  { name: "West Virginia", mascot: "Mountaineers", city: "Morgantown", state: "WV", zip: "26506", lat: 39.6295, lng: -79.9559, division: "D1", publicPrivate: "Public", conference: "Big 12", ranking: null, tuition: 9504, instagram: "@wvubaseball", xAccount: "@WVUBaseball", headCoach: "Randy Mazey", headCoachEmail: "baseball@mail.wvu.edu", asstCoach: "Steve Sabins", asstCoachEmail: "baseball@mail.wvu.edu", website: "https://wvusports.com/sports/baseball" },
  { name: "Kansas State", mascot: "Wildcats", city: "Manhattan", state: "KS", zip: "66506", lat: 39.1836, lng: -96.5717, division: "D1", publicPrivate: "Public", conference: "Big 12", ranking: null, tuition: 10383, instagram: "@kstatebaseball", xAccount: "@KStateBSB", headCoach: "Pete Hughes", headCoachEmail: "baseball@kstatesports.com", asstCoach: "Matt Angle", asstCoachEmail: "baseball@kstatesports.com", website: "https://kstatesports.com/sports/baseball" },
  { name: "Texas Tech", mascot: "Red Raiders", city: "Lubbock", state: "TX", zip: "79409", lat: 33.5843, lng: -101.8456, division: "D1", publicPrivate: "Public", conference: "Big 12", ranking: null, tuition: 11100, instagram: "@taboraseballl", xAccount: "@TTU_Baseball", headCoach: "Tim Tadlock", headCoachEmail: "baseball@ttu.edu", asstCoach: "J-Bob Thomas", asstCoachEmail: "baseball@ttu.edu", website: "https://texastech.com/sports/baseball" },
  { name: "Baylor", mascot: "Bears", city: "Waco", state: "TX", zip: "76798", lat: 31.5488, lng: -97.1131, division: "D1", publicPrivate: "Private", conference: "Big 12", ranking: null, tuition: 52348, instagram: "@baylorbaseball", xAccount: "@BaylorBaseball", headCoach: "Mitch Thompson", headCoachEmail: "baseball@baylor.edu", asstCoach: "Jon Strauss", asstCoachEmail: "baseball@baylor.edu", website: "https://baylorbears.com/sports/baseball" },
  { name: "UCF", mascot: "Knights", city: "Orlando", state: "FL", zip: "32816", lat: 28.6024, lng: -81.2001, division: "D1", publicPrivate: "Public", conference: "Big 12", ranking: null, tuition: 6368, instagram: "@ucf_baseball", xAccount: "@UCF_Baseball", headCoach: "Greg Lovelady", headCoachEmail: "baseball@ucf.edu", asstCoach: "Nick Ayers", asstCoachEmail: "baseball@ucf.edu", website: "https://ucfknights.com/sports/baseball" },
  { name: "Houston", mascot: "Cougars", city: "Houston", state: "TX", zip: "77204", lat: 29.7199, lng: -95.3422, division: "D1", publicPrivate: "Public", conference: "Big 12", ranking: null, tuition: 11590, instagram: "@uhcougarbb", xAccount: "@UHCougarBB", headCoach: "Todd Whitting", headCoachEmail: "baseball@uh.edu", asstCoach: "Trip Couch", asstCoachEmail: "baseball@uh.edu", website: "https://uhcougars.com/sports/baseball" },
  { name: "BYU", mascot: "Cougars", city: "Provo", state: "UT", zip: "84602", lat: 40.2518, lng: -111.6493, division: "D1", publicPrivate: "Private", conference: "Big 12", ranking: null, tuition: 6496, instagram: "@byubaseball", xAccount: "@BYUBaseball", headCoach: "Trent Pratt", headCoachEmail: "baseball@byu.edu", asstCoach: "Brent Haring", asstCoachEmail: "baseball@byu.edu", website: "https://byucougars.com/sports/baseball" },
  { name: "Cincinnati", mascot: "Bearcats", city: "Cincinnati", state: "OH", zip: "45221", lat: 39.1329, lng: -84.5150, division: "D1", publicPrivate: "Public", conference: "Big 12", ranking: null, tuition: 11000, instagram: "@gobearcatsbbq", xAccount: "@GoBEARCATSBSB", headCoach: "Connor Barth", headCoachEmail: "baseball@uc.edu", asstCoach: "Dan Bautista", asstCoachEmail: "baseball@uc.edu", website: "https://gobearcats.com/sports/baseball" },
  { name: "Arizona State", mascot: "Sun Devils", city: "Tempe", state: "AZ", zip: "85287", lat: 33.4242, lng: -111.9281, division: "D1", publicPrivate: "Public", conference: "Big 12", ranking: null, tuition: 11338, instagram: "@sundevilbsb", xAccount: "@ASU_Baseball", headCoach: "Willie Bloomquist", headCoachEmail: "baseball@asu.edu", asstCoach: "Michael Early", asstCoachEmail: "baseball@asu.edu", website: "https://thesundevils.com/sports/baseball" },
  { name: "Arizona", mascot: "Wildcats", city: "Tucson", state: "AZ", zip: "85721", lat: 32.2319, lng: -110.9501, division: "D1", publicPrivate: "Public", conference: "Big 12", ranking: null, tuition: 12467, instagram: "@arizonabaseball", xAccount: "@ArizonaBaseball", headCoach: "Chip Hale", headCoachEmail: "baseball@arizona.edu", asstCoach: "Dave Lawn", asstCoachEmail: "baseball@arizona.edu", website: "https://arizonawildcats.com/sports/baseball" },
  { name: "Colorado", mascot: "Buffaloes", city: "Boulder", state: "CO", zip: "80309", lat: 40.0076, lng: -105.2659, division: "D1", publicPrivate: "Public", conference: "Big 12", ranking: null, tuition: 12500, instagram: "@cubuffsbaseball", xAccount: "@CUBuffsBaseball", headCoach: "Mike Main", headCoachEmail: "baseball@colorado.edu", asstCoach: "Ryan Garvey", asstCoachEmail: "baseball@colorado.edu", website: "https://cubuffs.com/sports/baseball" },
  { name: "Utah", mascot: "Utes", city: "Salt Lake City", state: "UT", zip: "84112", lat: 40.7649, lng: -111.8421, division: "D1", publicPrivate: "Public", conference: "Big 12", ranking: null, tuition: 9222, instagram: "@utahbaseball", xAccount: "@Utah_Baseball", headCoach: "Gary Henderson", headCoachEmail: "baseball@utah.edu", asstCoach: "Adam Pavkovich", asstCoachEmail: "baseball@utah.edu", website: "https://utahutes.com/sports/baseball" },
  { name: "Kansas", mascot: "Jayhawks", city: "Lawrence", state: "KS", zip: "66045", lat: 38.9543, lng: -95.2558, division: "D1", publicPrivate: "Public", conference: "Big 12", ranking: null, tuition: 11148, instagram: "@kubaseball", xAccount: "@KUBaseball", headCoach: "Dan Fitzgerald", headCoachEmail: "baseball@ku.edu", asstCoach: "Ryan Graves", asstCoachEmail: "baseball@ku.edu", website: "https://kuathletics.com/sports/baseball" },

  // Big Ten
  { name: "Oregon State", mascot: "Beavers", city: "Corvallis", state: "OR", zip: "97331", lat: 44.5646, lng: -123.2620, division: "D1", publicPrivate: "Public", conference: "Big Ten", ranking: 24, tuition: 11715, instagram: "@baboroaseballl", xAccount: "@BeaverBaseball", headCoach: "Mitch Canham", headCoachEmail: "baseball@oregonstate.edu", asstCoach: "Rich Dorman", asstCoachEmail: "baseball@oregonstate.edu", website: "https://osubeavers.com/sports/baseball" },
  { name: "Michigan", mascot: "Wolverines", city: "Ann Arbor", state: "MI", zip: "48109", lat: 42.2780, lng: -83.7382, division: "D1", publicPrivate: "Public", conference: "Big Ten", ranking: null, tuition: 16312, instagram: "@umichbaseball", xAccount: "@umaborichbaseballl", headCoach: "Erik Bakich", headCoachEmail: "baseball@umich.edu", asstCoach: "Nick Schnabel", asstCoachEmail: "baseball@umich.edu", website: "https://mgoblue.com/sports/baseball" },
  { name: "Indiana", mascot: "Hoosiers", city: "Bloomington", state: "IN", zip: "47405", lat: 39.1682, lng: -86.5186, division: "D1", publicPrivate: "Public", conference: "Big Ten", ranking: null, tuition: 10708, instagram: "@indianabsb", xAccount: "@IndianaBase", headCoach: "Jeff Mercer", headCoachEmail: "baseball@indiana.edu", asstCoach: "Morgan Hopewell", asstCoachEmail: "baseball@indiana.edu", website: "https://iuhoosiers.com/sports/baseball" },
  { name: "Ohio State", mascot: "Buckeyes", city: "Columbus", state: "OH", zip: "43210", lat: 40.0066, lng: -83.0305, division: "D1", publicPrivate: "Public", conference: "Big Ten", ranking: null, tuition: 11936, instagram: "@ohiostatebaseball", xAccount: "@OhioStateBASE", headCoach: "Bill Mosiello", headCoachEmail: "baseball@osu.edu", asstCoach: "Matt Carpenter", asstCoachEmail: "baseball@osu.edu", website: "https://ohiostatebuckeyes.com/sports/baseball" },
  { name: "Nebraska", mascot: "Cornhuskers", city: "Lincoln", state: "NE", zip: "68588", lat: 40.8202, lng: -96.7005, division: "D1", publicPrivate: "Public", conference: "Big Ten", ranking: null, tuition: 9242, instagram: "@haboruskerbaseballl", xAccount: "@Husaborker_Baseballl", headCoach: "Will Bolt", headCoachEmail: "baseball@huskers.com", asstCoach: "Jeff Christy", asstCoachEmail: "baseball@huskers.com", website: "https://huskers.com/sports/baseball" },
  { name: "Maryland", mascot: "Terrapins", city: "College Park", state: "MD", zip: "20742", lat: 38.9860, lng: -76.9447, division: "D1", publicPrivate: "Public", conference: "Big Ten", ranking: null, tuition: 10779, instagram: "@taborerpsbaseball", xAccount: "@TerpsBaseball", headCoach: "Matt Swope", headCoachEmail: "baseball@umd.edu", asstCoach: "Corey Muscara", asstCoachEmail: "baseball@umd.edu", website: "https://umterps.com/sports/baseball" },
  { name: "Iowa", mascot: "Hawkeyes", city: "Iowa City", state: "IA", zip: "52242", lat: 41.6611, lng: -91.5302, division: "D1", publicPrivate: "Public", conference: "Big Ten", ranking: null, tuition: 9942, instagram: "@uiowabaseball", xAccount: "@UIBaseball", headCoach: "Rick Heller", headCoachEmail: "baseball@hawkeyesports.com", asstCoach: "Marty Sutherland", asstCoachEmail: "baseball@hawkeyesports.com", website: "https://hawkeyesports.com/sports/baseball" },
  { name: "Minnesota", mascot: "Golden Gophers", city: "Minneapolis", state: "MN", zip: "55455", lat: 44.9740, lng: -93.2277, division: "D1", publicPrivate: "Public", conference: "Big Ten", ranking: null, tuition: 15027, instagram: "@gaboropherbaseballl", xAccount: "@GopherBaseball", headCoach: "Ty Johnson", headCoachEmail: "baseball@umn.edu", asstCoach: "Garza Roberts", asstCoachEmail: "baseball@umn.edu", website: "https://gophersports.com/sports/baseball" },
  { name: "Penn State", mascot: "Nittany Lions", city: "University Park", state: "PA", zip: "16802", lat: 40.7982, lng: -77.8599, division: "D1", publicPrivate: "Public", conference: "Big Ten", ranking: null, tuition: 18898, instagram: "@pennstatebaseball", xAccount: "@PennStateBASE", headCoach: "Rob Cooper", headCoachEmail: "baseball@psu.edu", asstCoach: "Tyler Etcheberry", asstCoachEmail: "baseball@psu.edu", website: "https://gopsusports.com/sports/baseball" },
  { name: "Michigan State", mascot: "Spartans", city: "East Lansing", state: "MI", zip: "48824", lat: 42.7018, lng: -84.4822, division: "D1", publicPrivate: "Public", conference: "Big Ten", ranking: null, tuition: 14460, instagram: "@maborsu_baseballl", xAccount: "@MSU_Baseball", headCoach: "Adam Nightingale", headCoachEmail: "baseball@ath.msu.edu", asstCoach: "Graham Sikes", asstCoachEmail: "baseball@ath.msu.edu", website: "https://msuspartans.com/sports/baseball" },
  { name: "Purdue", mascot: "Boilermakers", city: "West Lafayette", state: "IN", zip: "47907", lat: 40.4237, lng: -86.9212, division: "D1", publicPrivate: "Public", conference: "Big Ten", ranking: null, tuition: 9992, instagram: "@purduebaseball", xAccount: "@PurdueBaseball", headCoach: "Greg Goff", headCoachEmail: "baseball@purdue.edu", asstCoach: "Ryan Hesters", asstCoachEmail: "baseball@purdue.edu", website: "https://purduesports.com/sports/baseball" },
  { name: "Rutgers", mascot: "Scarlet Knights", city: "Piscataway", state: "NJ", zip: "08854", lat: 40.5008, lng: -74.4474, division: "D1", publicPrivate: "Public", conference: "Big Ten", ranking: null, tuition: 15407, instagram: "@rutgersbaseball", xAccount: "@RutgersBase", headCoach: "Steve Owens", headCoachEmail: "baseball@scarletknights.com", asstCoach: "Phil Cundari", asstCoachEmail: "baseball@scarletknights.com", website: "https://scarletknights.com/sports/baseball" },
  { name: "Northwestern", mascot: "Wildcats", city: "Evanston", state: "IL", zip: "60208", lat: 42.0565, lng: -87.6753, division: "D1", publicPrivate: "Private", conference: "Big Ten", ranking: null, tuition: 63468, instagram: "@nubaseball", xAccount: "@NUCatsBaseball", headCoach: "Jim Foster", headCoachEmail: "baseball@northwestern.edu", asstCoach: "Josh Reynolds", asstCoachEmail: "baseball@northwestern.edu", website: "https://nusports.com/sports/baseball" },
  { name: "Illinois", mascot: "Fighting Illini", city: "Champaign", state: "IL", zip: "61820", lat: 40.1020, lng: -88.2272, division: "D1", publicPrivate: "Public", conference: "Big Ten", ranking: null, tuition: 15094, instagram: "@illinoisbaseball", xAccount: "@IlliniBaseball", headCoach: "Dan Hartleb", headCoachEmail: "baseball@illinois.edu", asstCoach: "Drew Dickinson", asstCoachEmail: "baseball@illinois.edu", website: "https://fightingillini.com/sports/baseball" },
  { name: "USC", mascot: "Trojans", city: "Los Angeles", state: "CA", zip: "90089", lat: 34.0224, lng: -118.2851, division: "D1", publicPrivate: "Private", conference: "Big Ten", ranking: null, tuition: 64726, instagram: "@usc_baseball", xAccount: "@USC_Baseball", headCoach: "Jason Gill", headCoachEmail: "baseball@usc.edu", asstCoach: "Ted Silva", asstCoachEmail: "baseball@usc.edu", website: "https://usctrojans.com/sports/baseball" },
  { name: "UCLA", mascot: "Bruins", city: "Los Angeles", state: "CA", zip: "90095", lat: 34.0689, lng: -118.4452, division: "D1", publicPrivate: "Public", conference: "Big Ten", ranking: null, tuition: 13804, instagram: "@uclabaseball", xAccount: "@UCLABaseball", headCoach: "John Savage", headCoachEmail: "baseball@athletics.ucla.edu", asstCoach: "Rex Peters", asstCoachEmail: "baseball@athletics.ucla.edu", website: "https://uclabruins.com/sports/baseball" },
  { name: "Washington", mascot: "Huskies", city: "Seattle", state: "WA", zip: "98195", lat: 47.6553, lng: -122.3035, division: "D1", publicPrivate: "Public", conference: "Big Ten", ranking: null, tuition: 12076, instagram: "@uw_baseball", xAccount: "@UW_Baseball", headCoach: "Jason Kelly", headCoachEmail: "baseball@uw.edu", asstCoach: "Elliott Cribby", asstCoachEmail: "baseball@uw.edu", website: "https://gohuskies.com/sports/baseball" },
  { name: "Oregon", mascot: "Ducks", city: "Eugene", state: "OR", zip: "97403", lat: 44.0448, lng: -123.0726, division: "D1", publicPrivate: "Public", conference: "Big Ten", ranking: null, tuition: 12720, instagram: "@oregonbaseball", xAccount: "@OregonBaseball", headCoach: "Mark Wasikowski", headCoachEmail: "baseball@uoregon.edu", asstCoach: "Jake Angier", asstCoachEmail: "baseball@uoregon.edu", website: "https://goducks.com/sports/baseball" },

  // Other D1 Conferences
  { name: "East Carolina", mascot: "Pirates", city: "Greenville", state: "NC", zip: "27858", lat: 35.6127, lng: -77.3664, division: "D1", publicPrivate: "Public", conference: "American Athletic", ranking: null, tuition: 7272, instagram: "@ecubaseball", xAccount: "@ECUBaseball", headCoach: "Cliff Godwin", headCoachEmail: "baseball@ecu.edu", asstCoach: "Jeff Palumbo", asstCoachEmail: "baseball@ecu.edu", website: "https://ecupirates.com/sports/baseball" },
  { name: "Tulane", mascot: "Green Wave", city: "New Orleans", state: "LA", zip: "70118", lat: 29.9399, lng: -90.1198, division: "D1", publicPrivate: "Private", conference: "American Athletic", ranking: null, tuition: 60814, instagram: "@tulabaseballl", xAccount: "@GreenWaveBSB", headCoach: "Travis Jewett", headCoachEmail: "baseball@tulane.edu", asstCoach: "Eddie Smith", asstCoachEmail: "baseball@tulane.edu", website: "https://tulanegreenwave.com/sports/baseball" },
  { name: "Wichita State", mascot: "Shockers", city: "Wichita", state: "KS", zip: "67260", lat: 37.7178, lng: -97.2921, division: "D1", publicPrivate: "Public", conference: "American Athletic", ranking: null, tuition: 8367, instagram: "@goshockersbsb", xAccount: "@GoShockersBSB", headCoach: "Brian Green", headCoachEmail: "baseball@goshockers.com", asstCoach: "Mike Sirianni", asstCoachEmail: "baseball@goshockers.com", website: "https://goshockers.com/sports/baseball" },
  { name: "Memphis", mascot: "Tigers", city: "Memphis", state: "TN", zip: "38152", lat: 35.1188, lng: -89.9373, division: "D1", publicPrivate: "Public", conference: "American Athletic", ranking: null, tuition: 9817, instagram: "@memaborophisbaseball", xAccount: "@MemphisBase", headCoach: "Kerrick Jackson", headCoachEmail: "baseball@memphis.edu", asstCoach: "Jeremy Baughman", asstCoachEmail: "baseball@memphis.edu", website: "https://gotigersgo.com/sports/baseball" },
  { name: "Coastal Carolina", mascot: "Chanticleers", city: "Conway", state: "SC", zip: "29528", lat: 33.7948, lng: -79.0142, division: "D1", publicPrivate: "Public", conference: "Sun Belt", ranking: null, tuition: 12060, instagram: "@ccubaseball", xAccount: "@CoastalBaseball", headCoach: "Gary Gilmore", headCoachEmail: "baseball@coastal.edu", asstCoach: "Drew Thomas", asstCoachEmail: "baseball@coastal.edu", website: "https://goccusports.com/sports/baseball" },
  { name: "Louisiana", mascot: "Ragin' Cajuns", city: "Lafayette", state: "LA", zip: "70504", lat: 30.2101, lng: -92.0198, division: "D1", publicPrivate: "Public", conference: "Sun Belt", ranking: null, tuition: 10584, instagram: "@raboraginbaseballl", xAccount: "@RaginCajunsBSB", headCoach: "Matt Deggs", headCoachEmail: "baseball@louisiana.edu", asstCoach: "Anthony Babineaux", asstCoachEmail: "baseball@louisiana.edu", website: "https://ragincajuns.com/sports/baseball" },
  { name: "Georgia Southern", mascot: "Eagles", city: "Statesboro", state: "GA", zip: "30458", lat: 32.4227, lng: -81.7832, division: "D1", publicPrivate: "Public", conference: "Sun Belt", ranking: null, tuition: 6234, instagram: "@gaborso_baseballl", xAccount: "@GSAthletics_BSB", headCoach: "Rodney Hennon", headCoachEmail: "baseball@georgiasouthern.edu", asstCoach: "A.J. Battisto", asstCoachEmail: "baseball@georgiasouthern.edu", website: "https://gseagles.com/sports/baseball" },
  { name: "Dallas Baptist", mascot: "Patriots", city: "Dallas", state: "TX", zip: "75211", lat: 32.7204, lng: -96.8953, division: "D1", publicPrivate: "Private", conference: "Conference USA", ranking: null, tuition: 32960, instagram: "@dbupatriots", xAccount: "@DBU_Baseball", headCoach: "Dan Heefner", headCoachEmail: "baseball@dbu.edu", asstCoach: "Ryan Stegall", asstCoachEmail: "baseball@dbu.edu", website: "https://dbupatriots.com/sports/baseball" },
  { name: "Gonzaga", mascot: "Bulldogs", city: "Spokane", state: "WA", zip: "99258", lat: 47.6671, lng: -117.4024, division: "D1", publicPrivate: "Private", conference: "West Coast", ranking: null, tuition: 52240, instagram: "@zagbaseball", xAccount: "@ZagBaseball", headCoach: "Mark Machtolf", headCoachEmail: "baseball@gonzaga.edu", asstCoach: "Brandon Harmon", asstCoachEmail: "baseball@gonzaga.edu", website: "https://gozags.com/sports/baseball" },
  { name: "Connecticut", mascot: "Huskies", city: "Storrs", state: "CT", zip: "06269", lat: 41.8084, lng: -72.2495, division: "D1", publicPrivate: "Public", conference: "Big East", ranking: null, tuition: 17226, instagram: "@uconnbsb", xAccount: "@UConnBSB", headCoach: "Jim Penders", headCoachEmail: "baseball@uconn.edu", asstCoach: "Jeff Hourigan", asstCoachEmail: "baseball@uconn.edu", website: "https://uconnhuskies.com/sports/baseball" },
  { name: "Creighton", mascot: "Bluejays", city: "Omaha", state: "NE", zip: "68178", lat: 41.2565, lng: -95.9345, division: "D1", publicPrivate: "Private", conference: "Big East", ranking: null, tuition: 44580, instagram: "@creightonbaseball", xAccount: "@CREIGHTONbball", headCoach: "Ed Servais", headCoachEmail: "baseball@creighton.edu", asstCoach: "Connor Gandossy", asstCoachEmail: "baseball@creighton.edu", website: "https://gocreighton.com/sports/baseball" },
  { name: "Liberty", mascot: "Flames", city: "Lynchburg", state: "VA", zip: "24515", lat: 37.3526, lng: -79.1817, division: "D1", publicPrivate: "Private", conference: "Conference USA", ranking: null, tuition: 24800, instagram: "@libertybaseball", xAccount: "@LibertyBSB", headCoach: "Scott Jackson", headCoachEmail: "baseball@liberty.edu", asstCoach: "Tim Benkert", asstCoachEmail: "baseball@liberty.edu", website: "https://libertyflames.com/sports/baseball" },
  { name: "San Diego", mascot: "Toreros", city: "San Diego", state: "CA", zip: "92110", lat: 32.7714, lng: -117.1898, division: "D1", publicPrivate: "Private", conference: "West Coast", ranking: null, tuition: 55480, instagram: "@usdbaseball", xAccount: "@USDBball", headCoach: "Brock Ungricht", headCoachEmail: "baseball@sandiego.edu", asstCoach: "Sam Wolff", asstCoachEmail: "baseball@sandiego.edu", website: "https://usdtoreros.com/sports/baseball" },
  { name: "Long Beach State", mascot: "Beach", city: "Long Beach", state: "CA", zip: "90840", lat: 33.7838, lng: -118.1141, division: "D1", publicPrivate: "Public", conference: "Big West", ranking: null, tuition: 6798, instagram: "@lbsubaseball", xAccount: "@LBSUBaseball", headCoach: "Eric Valenzuela", headCoachEmail: "baseball@csulb.edu", asstCoach: "Troy Nakamura", asstCoachEmail: "baseball@csulb.edu", website: "https://longbeachstate.com/sports/baseball" },
  { name: "UC Irvine", mascot: "Anteaters", city: "Irvine", state: "CA", zip: "92697", lat: 33.6405, lng: -117.8443, division: "D1", publicPrivate: "Public", conference: "Big West", ranking: null, tuition: 13727, instagram: "@ucibaseball", xAccount: "@UCIBaseball", headCoach: "Ben Orloff", headCoachEmail: "baseball@uci.edu", asstCoach: "Matt McDonald", asstCoachEmail: "baseball@uci.edu", website: "https://ucirvinesports.com/sports/baseball" },
  { name: "Cal State Fullerton", mascot: "Titans", city: "Fullerton", state: "CA", zip: "92831", lat: 33.8829, lng: -117.8869, division: "D1", publicPrivate: "Public", conference: "Big West", ranking: null, tuition: 6907, instagram: "@fullertonbaseball", xAccount: "@FullertonBSB", headCoach: "Jason Dietrich", headCoachEmail: "baseball@fullerton.edu", asstCoach: "Chad Baum", asstCoachEmail: "baseball@fullerton.edu", website: "https://fullertontitans.com/sports/baseball" },
  { name: "San Diego State", mascot: "Aztecs", city: "San Diego", state: "CA", zip: "92182", lat: 32.7757, lng: -117.0719, division: "D1", publicPrivate: "Public", conference: "Mountain West", ranking: null, tuition: 7510, instagram: "@aztecbaseball", xAccount: "@AztecBaseball", headCoach: "Mike Martinez", headCoachEmail: "baseball@sdsu.edu", asstCoach: "Sam Peraza", asstCoachEmail: "baseball@sdsu.edu", website: "https://goaztecs.com/sports/baseball" },
  { name: "Fresno State", mascot: "Bulldogs", city: "Fresno", state: "CA", zip: "93740", lat: 36.8134, lng: -119.7486, division: "D1", publicPrivate: "Public", conference: "Mountain West", ranking: null, tuition: 6585, instagram: "@fresnostbaseball", xAccount: "@FresnoStBSB", headCoach: "Ryan Overland", headCoachEmail: "baseball@csufresno.edu", asstCoach: "Brad Marcelino", asstCoachEmail: "baseball@csufresno.edu", website: "https://gobulldogs.com/sports/baseball" },
  { name: "Hawai'i", mascot: "Rainbow Warriors", city: "Honolulu", state: "HI", zip: "96822", lat: 21.2969, lng: -157.8171, division: "D1", publicPrivate: "Public", conference: "Big West", ranking: null, tuition: 12186, instagram: "@hawaiibaseball", xAccount: "@HawaiiBaseball", headCoach: "Rich Hill", headCoachEmail: "baseball@hawaii.edu", asstCoach: "Carl Fraticelli", asstCoachEmail: "baseball@hawaii.edu", website: "https://hawaiiathletics.com/sports/baseball" },
  { name: "Louisiana Tech", mascot: "Bulldogs", city: "Ruston", state: "LA", zip: "71272", lat: 32.5293, lng: -92.6380, division: "D1", publicPrivate: "Public", conference: "Conference USA", ranking: null, tuition: 9705, instagram: "@latechbsb", xAccount: "@LATechBSB", headCoach: "Lane Burroughs", headCoachEmail: "baseball@latech.edu", asstCoach: "Chris Frey", asstCoachEmail: "baseball@latech.edu", website: "https://latechsports.com/sports/baseball" },
  { name: "Southern Miss", mascot: "Golden Eagles", city: "Hattiesburg", state: "MS", zip: "39406", lat: 31.3271, lng: -89.3376, division: "D1", publicPrivate: "Public", conference: "Sun Belt", ranking: null, tuition: 9316, instagram: "@southernmissbs", xAccount: "@SouthernMissBSB", headCoach: "Scott Berry", headCoachEmail: "baseball@usm.edu", asstCoach: "Travis Creel", asstCoachEmail: "baseball@usm.edu", website: "https://southernmiss.com/sports/baseball" },

  // ============================================
  // NCAA DIVISION II PROGRAMS (sample)
  // ============================================
  { name: "Tampa", mascot: "Spartans", city: "Tampa", state: "FL", zip: "33606", lat: 27.9467, lng: -82.4711, division: "D2", publicPrivate: "Private", conference: "Sunshine State", ranking: null, tuition: 30658, instagram: "@tampaspartansbb", xAccount: "@TampaSpartanBB", headCoach: "Joe Urso", headCoachEmail: "baseball@ut.edu", asstCoach: "Nelson North", asstCoachEmail: "baseball@ut.edu", website: "https://tampaspartans.com/sports/baseball" },
  { name: "Central Missouri", mascot: "Mules", city: "Warrensburg", state: "MO", zip: "64093", lat: 38.7631, lng: -93.7360, division: "D2", publicPrivate: "Public", conference: "MIAA", ranking: null, tuition: 7871, instagram: "@ucmbaseball", xAccount: "@UCMBaseball", headCoach: "Kyle Crookes", headCoachEmail: "baseball@ucmo.edu", asstCoach: "Nolan Hadley", asstCoachEmail: "baseball@ucmo.edu", website: "https://ucmathletics.com/sports/baseball" },
  { name: "West Florida", mascot: "Argonauts", city: "Pensacola", state: "FL", zip: "32514", lat: 30.5482, lng: -87.2186, division: "D2", publicPrivate: "Public", conference: "Gulf South", ranking: null, tuition: 6360, instagram: "@uwfbaseball", xAccount: "@UWFBaseball", headCoach: "Steve Frey", headCoachEmail: "baseball@uwf.edu", asstCoach: "Tim Montez", asstCoachEmail: "baseball@uwf.edu", website: "https://goargos.com/sports/baseball" },
  { name: "North Greenville", mascot: "Crusaders", city: "Tigerville", state: "SC", zip: "29688", lat: 35.0666, lng: -82.3682, division: "D2", publicPrivate: "Private", conference: "Conference Carolinas", ranking: null, tuition: 20100, instagram: "@ngucrusadersbsb", xAccount: "@NGU_Baseball", headCoach: "Landon Powell", headCoachEmail: "baseball@ngu.edu", asstCoach: "Jeff McKay", asstCoachEmail: "baseball@ngu.edu", website: "https://ngucrusaders.com/sports/baseball" },
  { name: "Augustana (SD)", mascot: "Vikings", city: "Sioux Falls", state: "SD", zip: "57197", lat: 43.5650, lng: -96.7258, division: "D2", publicPrivate: "Private", conference: "NSIC", ranking: null, tuition: 37790, instagram: "@augiebb", xAccount: "@AugieBB", headCoach: "Tim Huber", headCoachEmail: "baseball@augie.edu", asstCoach: "Brent Burgess", asstCoachEmail: "baseball@augie.edu", website: "https://goaugie.com/sports/baseball" },
  { name: "Colorado Mesa", mascot: "Mavericks", city: "Grand Junction", state: "CO", zip: "81501", lat: 39.0831, lng: -108.5507, division: "D2", publicPrivate: "Public", conference: "RMAC", ranking: null, tuition: 9488, instagram: "@cmumavbaseball", xAccount: "@CMUMavBaseball", headCoach: "Chris Hanks", headCoachEmail: "baseball@coloradomesa.edu", asstCoach: "Andrew Tull", asstCoachEmail: "baseball@coloradomesa.edu", website: "https://cmumavericks.com/sports/baseball" },
  { name: "Southern New Hampshire", mascot: "Penmen", city: "Manchester", state: "NH", zip: "03106", lat: 42.9801, lng: -71.4528, division: "D2", publicPrivate: "Private", conference: "NE-10", ranking: null, tuition: 38922, instagram: "@snhubaseball", xAccount: "@SNHUBaseball", headCoach: "Scott Loiseau", headCoachEmail: "baseball@snhu.edu", asstCoach: "Todd & Gagne", asstCoachEmail: "baseball@snhu.edu", website: "https://snhupenmen.com/sports/baseball" },
  { name: "Angelo State", mascot: "Rams", city: "San Angelo", state: "TX", zip: "76909", lat: 31.4399, lng: -100.4559, division: "D2", publicPrivate: "Public", conference: "Lone Star", ranking: null, tuition: 8848, instagram: "@angelostatebaseball", xAccount: "@AngeloStateBSB", headCoach: "Kevin Brooks", headCoachEmail: "baseball@angelo.edu", asstCoach: "Shawn Ball", asstCoachEmail: "baseball@angelo.edu", website: "https://angelosports.com/sports/baseball" },
  { name: "Wingate", mascot: "Bulldogs", city: "Wingate", state: "NC", zip: "28174", lat: 34.9844, lng: -80.4490, division: "D2", publicPrivate: "Private", conference: "South Atlantic", ranking: null, tuition: 38830, instagram: "@wingatebaseball", xAccount: "@WingateBSB", headCoach: "Todd Interdonato", headCoachEmail: "baseball@wingate.edu", asstCoach: "Kevin Erminio", asstCoachEmail: "baseball@wingate.edu", website: "https://wingatebulldogs.com/sports/baseball" },
  { name: "Rollins", mascot: "Tars", city: "Winter Park", state: "FL", zip: "32789", lat: 28.5964, lng: -81.3489, division: "D2", publicPrivate: "Private", conference: "Sunshine State", ranking: null, tuition: 42850, instagram: "@rollinsbaseball", xAccount: "@RollinsBSB", headCoach: "Jon Sjogren", headCoachEmail: "baseball@rollins.edu", asstCoach: "Ryan Fecteau", asstCoachEmail: "baseball@rollins.edu", website: "https://rollinssports.com/sports/baseball" },
  { name: "Catawba", mascot: "Indians", city: "Salisbury", state: "NC", zip: "28144", lat: 35.6707, lng: -80.4745, division: "D2", publicPrivate: "Private", conference: "South Atlantic", ranking: null, tuition: 33750, instagram: "@catawobabaseball", xAccount: "@CatawbaBSB", headCoach: "Jim Gantt", headCoachEmail: "baseball@catawba.edu", asstCoach: "PJ Martino", asstCoachEmail: "baseball@catawba.edu", website: "https://gocatawbaindians.com/sports/baseball" },
  { name: "Nova Southeastern", mascot: "Sharks", city: "Fort Lauderdale", state: "FL", zip: "33314", lat: 26.0773, lng: -80.2417, division: "D2", publicPrivate: "Private", conference: "Sunshine State", ranking: null, tuition: 35290, instagram: "@nsusharksbsb", xAccount: "@NSU_Baseball", headCoach: "Laz Gutierrez", headCoachEmail: "baseball@nova.edu", asstCoach: "Eric Cruz", asstCoachEmail: "baseball@nova.edu", website: "https://nsusharks.com/sports/baseball" },
  { name: "UC San Diego", mascot: "Tritons", city: "La Jolla", state: "CA", zip: "92093", lat: 32.8801, lng: -117.2340, division: "D2", publicPrivate: "Public", conference: "CCAA", ranking: null, tuition: 14451, instagram: "@ucsdbaseball", xAccount: "@UCSDBsb", headCoach: "Eric Newman", headCoachEmail: "baseball@ucsd.edu", asstCoach: "Kevin Couture", asstCoachEmail: "baseball@ucsd.edu", website: "https://ucsdtritons.com/sports/baseball" },
  { name: "West Texas A&M", mascot: "Buffaloes", city: "Canyon", state: "TX", zip: "79016", lat: 34.9804, lng: -101.9181, division: "D2", publicPrivate: "Public", conference: "Lone Star", ranking: null, tuition: 8338, instagram: "@wtamubaseball", xAccount: "@WTBaseballl", headCoach: "Matt Parker", headCoachEmail: "baseball@wtamu.edu", asstCoach: "Clay Davis", asstCoachEmail: "baseball@wtamu.edu", website: "https://gobuffsgo.com/sports/baseball" },
  { name: "Valdosta State", mascot: "Blazers", city: "Valdosta", state: "GA", zip: "31698", lat: 30.8507, lng: -83.2897, division: "D2", publicPrivate: "Public", conference: "Gulf South", ranking: null, tuition: 7464, instagram: "@vstatebaseball", xAccount: "@VStateBSB", headCoach: "Greg & Nourse", headCoachEmail: "baseball@valdosta.edu", asstCoach: "Brian Thomas", asstCoachEmail: "baseball@valdosta.edu", website: "https://vstateblazers.com/sports/baseball" },

  // ============================================
  // NCAA DIVISION III PROGRAMS (sample)
  // ============================================
  { name: "Salisbury", mascot: "Sea Gulls", city: "Salisbury", state: "MD", zip: "21801", lat: 38.3754, lng: -75.6074, division: "D3", publicPrivate: "Public", conference: "Coast-to-Coast Athletic", ranking: null, tuition: 10086, instagram: "@salisburybaseball", xAccount: "@SalisburyBSB", headCoach: "Troy Brohawn", headCoachEmail: "baseball@salisbury.edu", asstCoach: "Jason Leffler", asstCoachEmail: "baseball@salisbury.edu", website: "https://salisburyseagulls.com/sports/baseball" },
  { name: "Trinity (TX)", mascot: "Tigers", city: "San Antonio", state: "TX", zip: "78212", lat: 29.4614, lng: -98.4832, division: "D3", publicPrivate: "Private", conference: "SCAC", ranking: null, tuition: 49590, instagram: "@trinitybaseball", xAccount: "@TrinityBSB", headCoach: "Tim Scannell", headCoachEmail: "baseball@trinity.edu", asstCoach: "Ryan Shotzberger", asstCoachEmail: "baseball@trinity.edu", website: "https://trinitytigers.com/sports/baseball" },
  { name: "Birmingham-Southern", mascot: "Panthers", city: "Birmingham", state: "AL", zip: "35254", lat: 33.5093, lng: -86.8474, division: "D3", publicPrivate: "Private", conference: "SAA", ranking: null, tuition: 20050, instagram: "@bscbaseball", xAccount: "@BSC_Baseball", headCoach: "Jan Weisberg", headCoachEmail: "baseball@bsc.edu", asstCoach: "Chase Dungan", asstCoachEmail: "baseball@bsc.edu", website: "https://bscsports.net/sports/baseball" },
  { name: "Chapman", mascot: "Panthers", city: "Orange", state: "CA", zip: "92866", lat: 33.7940, lng: -117.8514, division: "D3", publicPrivate: "Private", conference: "SCIAC", ranking: null, tuition: 59730, instagram: "@chapmanbaseball", xAccount: "@CUPantherBSB", headCoach: "Scott Laverty", headCoachEmail: "baseball@chapman.edu", asstCoach: "Randy Keefer", asstCoachEmail: "baseball@chapman.edu", website: "https://chapmanathletics.com/sports/baseball" },
  { name: "Emory", mascot: "Eagles", city: "Atlanta", state: "GA", zip: "30322", lat: 33.7963, lng: -84.3234, division: "D3", publicPrivate: "Private", conference: "UAA", ranking: null, tuition: 57948, instagram: "@emorybaseball", xAccount: "@EmoryBSB", headCoach: "Mike Twardoski", headCoachEmail: "baseball@emory.edu", asstCoach: "Josh Bloomer", asstCoachEmail: "baseball@emory.edu", website: "https://emoryathletics.com/sports/baseball" },
  { name: "Johns Hopkins", mascot: "Blue Jays", city: "Baltimore", state: "MD", zip: "21218", lat: 39.3299, lng: -76.6205, division: "D3", publicPrivate: "Private", conference: "Centennial", ranking: null, tuition: 60480, instagram: "@hopkinsbaseball", xAccount: "@HopkinsBSB", headCoach: "Bob Babb", headCoachEmail: "baseball@jhu.edu", asstCoach: "Patrick Cherry", asstCoachEmail: "baseball@jhu.edu", website: "https://hopkinssports.com/sports/baseball" },
  { name: "UW-Whitewater", mascot: "Warhawks", city: "Whitewater", state: "WI", zip: "53190", lat: 42.8336, lng: -88.7326, division: "D3", publicPrivate: "Public", conference: "WIAC", ranking: null, tuition: 8099, instagram: "@uwwbaseball", xAccount: "@UWWBaseball", headCoach: "John Vodenlich", headCoachEmail: "baseball@uww.edu", asstCoach: "Kyle Barker", asstCoachEmail: "baseball@uww.edu", website: "https://uwwsports.com/sports/baseball" },
  { name: "SUNY Cortland", mascot: "Red Dragons", city: "Cortland", state: "NY", zip: "13045", lat: 42.5917, lng: -76.1831, division: "D3", publicPrivate: "Public", conference: "SUNYAC", ranking: null, tuition: 8866, instagram: "@cortlandbaseball", xAccount: "@CortlandBSB", headCoach: "Joe Brown", headCoachEmail: "baseball@cortland.edu", asstCoach: "Drew Kent", asstCoachEmail: "baseball@cortland.edu", website: "https://cortlandreddragons.com/sports/baseball" },
  { name: "Tufts", mascot: "Jumbos", city: "Medford", state: "MA", zip: "02155", lat: 42.4074, lng: -71.1190, division: "D3", publicPrivate: "Private", conference: "NESCAC", ranking: null, tuition: 65222, instagram: "@tuftsbaseball", xAccount: "@TuftsBSB", headCoach: "Matt Noone", headCoachEmail: "baseball@tufts.edu", asstCoach: "Matt LaCasse", asstCoachEmail: "baseball@tufts.edu", website: "https://tuftsjumbos.com/sports/baseball" },
  { name: "Pomona-Pitzer", mascot: "Sagehens", city: "Claremont", state: "CA", zip: "91711", lat: 34.0967, lng: -117.7198, division: "D3", publicPrivate: "Private", conference: "SCIAC", ranking: null, tuition: 59520, instagram: "@paboromonabaseballl", xAccount: "@PPSagehens", headCoach: "Frank Marroquin", headCoachEmail: "baseball@pomona.edu", asstCoach: "Andrew Choi", asstCoachEmail: "baseball@pomona.edu", website: "https://sagehens.com/sports/baseball" },
  { name: "Randolph-Macon", mascot: "Yellow Jackets", city: "Ashland", state: "VA", zip: "23005", lat: 37.7590, lng: -77.4780, division: "D3", publicPrivate: "Private", conference: "ODAC", ranking: null, tuition: 45710, instagram: "@rmcbaseball", xAccount: "@RMC_BSB", headCoach: "Ray Hedrick", headCoachEmail: "baseball@rmc.edu", asstCoach: "Justin Thompson", asstCoachEmail: "baseball@rmc.edu", website: "https://rmcathletics.com/sports/baseball" },
  { name: "Rowan", mascot: "Profs", city: "Glassboro", state: "NJ", zip: "08028", lat: 39.7092, lng: -75.1199, division: "D3", publicPrivate: "Public", conference: "NJAC", ranking: null, tuition: 13878, instagram: "@rowanbaseball", xAccount: "@RowanBSB", headCoach: "Mike Dickson", headCoachEmail: "baseball@rowan.edu", asstCoach: "Jason Appel", asstCoachEmail: "baseball@rowan.edu", website: "https://rowanprofs.com/sports/baseball" },
  { name: "Shenandoah", mascot: "Hornets", city: "Winchester", state: "VA", zip: "22601", lat: 39.1832, lng: -78.1633, division: "D3", publicPrivate: "Private", conference: "ODAC", ranking: null, tuition: 38600, instagram: "@suhornetsbsb", xAccount: "@SU_HornetsBSB", headCoach: "Kevin Anderson", headCoachEmail: "baseball@su.edu", asstCoach: "Cabot Smith", asstCoachEmail: "baseball@su.edu", website: "https://suhornetathletics.com/sports/baseball" },
  { name: "Wheaton (IL)", mascot: "Thunder", city: "Wheaton", state: "IL", zip: "60187", lat: 41.8661, lng: -88.1070, division: "D3", publicPrivate: "Private", conference: "CCIW", ranking: null, tuition: 42050, instagram: "@wheatonbaseball", xAccount: "@WheatonBSB", headCoach: "Jake Wilson", headCoachEmail: "baseball@wheaton.edu", asstCoach: "Nolan Price", asstCoachEmail: "baseball@wheaton.edu", website: "https://wheatonthunder.com/sports/baseball" },
  { name: "Swarthmore", mascot: "Garnet", city: "Swarthmore", state: "PA", zip: "19081", lat: 39.9022, lng: -75.3499, division: "D3", publicPrivate: "Private", conference: "Centennial", ranking: null, tuition: 58256, instagram: "@swatbaseball", xAccount: "@SwatBSB", headCoach: "Paul Shortridge", headCoachEmail: "baseball@swarthmore.edu", asstCoach: "Quinn Holmes", asstCoachEmail: "baseball@swarthmore.edu", website: "https://swarthmoreathletics.com/sports/baseball" },

  // ============================================
  // JUNIOR COLLEGE (JUCO) PROGRAMS (sample)
  // ============================================
  { name: "San Jacinto", mascot: "Gators", city: "Pasadena", state: "TX", zip: "77505", lat: 29.6452, lng: -95.1507, division: "JUCO", publicPrivate: "Public", conference: "Region XIV", ranking: null, tuition: 2640, instagram: "@sjcbaseball", xAccount: "@SJCBaseball", headCoach: "Tom Arrington", headCoachEmail: "baseball@sjcd.edu", asstCoach: "Jay Cook", asstCoachEmail: "baseball@sjcd.edu", website: "https://sjcgatorsports.com/sports/baseball" },
  { name: "Chipola", mascot: "Indians", city: "Marianna", state: "FL", zip: "32446", lat: 30.7740, lng: -85.2199, division: "JUCO", publicPrivate: "Public", conference: "Panhandle", ranking: null, tuition: 3050, instagram: "@chipolabaseball", xAccount: "@ChipolaBSB", headCoach: "Jeff Johnson", headCoachEmail: "baseball@chipola.edu", asstCoach: "Ross McCarter", asstCoachEmail: "baseball@chipola.edu", website: "https://chipolaathletics.com/sports/baseball" },
  { name: "Iowa Western", mascot: "Reivers", city: "Council Bluffs", state: "IA", zip: "51503", lat: 41.2625, lng: -95.8608, division: "JUCO", publicPrivate: "Public", conference: "ICCAC", ranking: null, tuition: 4890, instagram: "@iwccbaseball", xAccount: "@IWCC_Baseball", headCoach: "Marc Rardin", headCoachEmail: "baseball@iwcc.edu", asstCoach: "Brady Schuck", asstCoachEmail: "baseball@iwcc.edu", website: "https://reiversports.com/sports/baseball" },
  { name: "Central Arizona", mascot: "Vaqueros", city: "Coolidge", state: "AZ", zip: "85128", lat: 32.9788, lng: -111.5263, division: "JUCO", publicPrivate: "Public", conference: "ACCAC", ranking: null, tuition: 2580, instagram: "@cazbaseball", xAccount: "@CAZBaseball", headCoach: "Cody Oakes", headCoachEmail: "baseball@centralaz.edu", asstCoach: "Matt Parrott", asstCoachEmail: "baseball@centralaz.edu", website: "https://cazvaqueros.com/sports/baseball" },
  { name: "McLennan", mascot: "Highlanders", city: "Waco", state: "TX", zip: "76708", lat: 31.5711, lng: -97.1514, division: "JUCO", publicPrivate: "Public", conference: "NTJCAC", ranking: null, tuition: 3280, instagram: "@mccbaseball", xAccount: "@MCC_BSB", headCoach: "Mitch Thompson", headCoachEmail: "baseball@mclennan.edu", asstCoach: "Jason Elam", asstCoachEmail: "baseball@mclennan.edu", website: "https://mcchighlanders.com/sports/baseball" },
  { name: "Northwest Florida State", mascot: "Raiders", city: "Niceville", state: "FL", zip: "32578", lat: 30.5095, lng: -86.4544, division: "JUCO", publicPrivate: "Public", conference: "Panhandle", ranking: null, tuition: 3120, instagram: "@nwfscbaseball", xAccount: "@NWFSCBaseball", headCoach: "Doug Martin", headCoachEmail: "baseball@nwfsc.edu", asstCoach: "Tyler Lehrmann", asstCoachEmail: "baseball@nwfsc.edu", website: "https://nwfraiders.com/sports/baseball" },
  { name: "Wabash Valley", mascot: "Warriors", city: "Mt. Carmel", state: "IL", zip: "62863", lat: 38.4105, lng: -87.7614, division: "JUCO", publicPrivate: "Public", conference: "GRAC", ranking: null, tuition: 4200, instagram: "@wvcbaseball", xAccount: "@WVC_Baseball", headCoach: "Rob Sobeski", headCoachEmail: "baseball@iecc.edu", asstCoach: "Matt Jones", asstCoachEmail: "baseball@iecc.edu", website: "https://wvcwarriors.com/sports/baseball" },
  { name: "Walters State", mascot: "Senators", city: "Morristown", state: "TN", zip: "37813", lat: 36.2125, lng: -83.2963, division: "JUCO", publicPrivate: "Public", conference: "TCCAA", ranking: null, tuition: 4550, instagram: "@wsccsbaseball", xAccount: "@WSCC_Baseball", headCoach: "D.J. Jones", headCoachEmail: "baseball@ws.edu", asstCoach: "Adam Lockridge", asstCoachEmail: "baseball@ws.edu", website: "https://wsccsenators.com/sports/baseball" },
  { name: "Crowder", mascot: "Roughriders", city: "Neosho", state: "MO", zip: "64850", lat: 36.8621, lng: -94.3842, division: "JUCO", publicPrivate: "Public", conference: "MCCAC", ranking: null, tuition: 3720, instagram: "@crowderbsb", xAccount: "@CrowderBSB", headCoach: "Travis Lallemand", headCoachEmail: "baseball@crowder.edu", asstCoach: "Adam Beinke", asstCoachEmail: "baseball@crowder.edu", website: "https://crowderathletics.com/sports/baseball" },
  { name: "Seminole State", mascot: "Trojans", city: "Seminole", state: "OK", zip: "74868", lat: 35.2403, lng: -96.6701, division: "JUCO", publicPrivate: "Public", conference: "OCAC", ranking: null, tuition: 4170, instagram: "@sscbaseball", xAccount: "@SSC_Baseball", headCoach: "Lloyd Simmons", headCoachEmail: "baseball@sscok.edu", asstCoach: "Paul Shortridge", asstCoachEmail: "baseball@sscok.edu", website: "https://sscathletics.com/sports/baseball" },
  { name: "Indian Hills", mascot: "Warriors", city: "Ottumwa", state: "IA", zip: "52501", lat: 41.0168, lng: -92.4113, division: "JUCO", publicPrivate: "Public", conference: "ICCAC", ranking: null, tuition: 5300, instagram: "@ihccbaseball", xAccount: "@IHCC_Baseball", headCoach: "Kody Cook", headCoachEmail: "baseball@indianhills.edu", asstCoach: "Ryan Boehmer", asstCoachEmail: "baseball@indianhills.edu", website: "https://ihccwarriors.com/sports/baseball" },
  { name: "Yavapai", mascot: "Roughriders", city: "Prescott", state: "AZ", zip: "86301", lat: 34.5400, lng: -112.4685, division: "JUCO", publicPrivate: "Public", conference: "ACCAC", ranking: null, tuition: 2430, instagram: "@yavapaibsb", xAccount: "@YavapaiBaseball", headCoach: "Ryan Cougill", headCoachEmail: "baseball@yc.edu", asstCoach: "Shane Murphy", asstCoachEmail: "baseball@yc.edu", website: "https://ycathletics.com/sports/baseball" },
  { name: "Grayson", mascot: "Vikings", city: "Denison", state: "TX", zip: "75020", lat: 33.7562, lng: -96.5665, division: "JUCO", publicPrivate: "Public", conference: "NTJCAC", ranking: null, tuition: 2856, instagram: "@graysonbaseball", xAccount: "@GraysonBSB", headCoach: "Dooley Womack", headCoachEmail: "baseball@grayson.edu", asstCoach: "Jason Martin", asstCoachEmail: "baseball@grayson.edu", website: "https://graysonvikings.com/sports/baseball" },
  { name: "Tallahassee", mascot: "Eagles", city: "Tallahassee", state: "FL", zip: "32304", lat: 30.4477, lng: -84.2906, division: "JUCO", publicPrivate: "Public", conference: "Panhandle", ranking: null, tuition: 3020, instagram: "@tccbaseball", xAccount: "@TCC_Baseball", headCoach: "Mike McLeod", headCoachEmail: "baseball@tcc.fl.edu", asstCoach: "Kevin McCall", asstCoachEmail: "baseball@tcc.fl.edu", website: "https://tccathletics.com/sports/baseball" },
  { name: "Tyler", mascot: "Apaches", city: "Tyler", state: "TX", zip: "75798", lat: 32.3121, lng: -95.2454, division: "JUCO", publicPrivate: "Public", conference: "Region XIV", ranking: null, tuition: 2700, instagram: "@tjcbaseball", xAccount: "@TJC_Baseball", headCoach: "Doug Wren", headCoachEmail: "baseball@tjc.edu", asstCoach: "Ryan Robbins", asstCoachEmail: "baseball@tjc.edu", website: "https://tjcapaches.com/sports/baseball" },
];

const insert = db.prepare(`
  INSERT INTO schools (name, mascot, city, state, zip, latitude, longitude, division, public_private, conference, current_ranking, tuition, instagram, x_account, head_coach_name, head_coach_email, assistant_coach_name, assistant_coach_email, website)
  VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`);

const insertMany = db.transaction((schools: SchoolSeed[]) => {
  for (const s of schools) {
    insert.run(
      s.name, s.mascot, s.city, s.state, s.zip, s.lat, s.lng,
      s.division, s.publicPrivate, s.conference, s.ranking, s.tuition,
      s.instagram, s.xAccount, s.headCoach, s.headCoachEmail,
      s.asstCoach, s.asstCoachEmail, s.website
    );
  }
});

insertMany(schools);

console.log(`Seeded ${schools.length} schools`);

// Show breakdown
const breakdown = db.prepare("SELECT division, COUNT(*) as count FROM schools GROUP BY division").all();
console.log("Breakdown by division:");
for (const row of breakdown as { division: string; count: number }[]) {
  console.log(`  ${row.division}: ${row.count} programs`);
}

db.close();
